# Netlify Configuration File

# Build settings
[build]
  publish = "."
  functions = "functions"

# Forms settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect rules for form success
[[redirects]]
  from = "/review-success"
  to = "/templates/review-success.html"
  status = 200

# API endpoints for serverless functions
[[redirects]]
  from = "/api/reviews/*"
  to = "/.netlify/functions/reviews/:splat"
  status = 200

[[redirects]]
  from = "/api/get-reviews/*"
  to = "/.netlify/functions/get-reviews/:splat"
  status = 200

# Handle form submissions
[[plugins]]
  package = "@netlify/plugin-forms"

# Environment variables (you can set these in Netlify dashboard)
[build.environment]
  NODE_VERSION = "18"

# Form detection
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Headers for API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Form handler settings
[forms]
  honeypot = "bot-field"
